version: '3.7'

services:
  lightlink_app:
    container_name: lightlink_app
    image: lightlink_app
    command: >
      sh -c "python manage.py migrate &&
             python lightlink/db_preset.py &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./lightlink/dev.env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/apps/lightlink/
    ports:
      - "8000:8000"
    expose:
      - 8000
    depends_on:
      - lightlink_db
      - lightlink_redis
  
  lightlink_db:
    container_name: lightlink_db
    image: postgres:14-alpine
    env_file:
      - ./lightlink/dev.env
    volumes:
      - lightlink_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    expose:
      - 5432
  
  lightlink_redis:
    container_name: lightlink_redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    expose:
      - 6379

  lightlink_media_server:
    container_name: lightlink_kurento
    image: kurento/kurento-media-server:6.17
    environment:
      - KMS_STUN_IP=stun.l.google.com
      - KMS_STUN_PORT=19302
    ports:
      - "8888:8888"
    expose:
      - 8888

volumes:
  lightlink_db_data:
    driver: "local"