# Generated by Django 4.2.4 on 2023-08-25 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendship',
            old_name='receiver_id',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='friendship',
            old_name='sender_id',
            new_name='sender',
        ),
        migrations.RenameField(
            model_name='friendship',
            old_name='status_type_id',
            new_name='status_type',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_id',
            new_name='user',
        ),
    ]
