# Generated by Django 4.2.4 on 2023-09-03 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video_chat', '0003_channel_channeltype_channelinfo_channel_channel_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelinfo',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_infos', to='video_chat.channel'),
        ),
        migrations.AlterField(
            model_name='channelinfo',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_infos', to='video_chat.profile'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_friendships', to='video_chat.profile'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_friendships', to='video_chat.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='channels',
            field=models.ManyToManyField(through='video_chat.ChannelInfo', to='video_chat.channel'),
        ),
    ]
