# Generated by Django 4.2.4 on 2023-10-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_chat', '0005_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_avatar',
            field=models.ImageField(default='default_profile_avatar', upload_to='profile_avatars'),
        ),
    ]
