# Generated by Django 4.2.4 on 2023-11-04 08:47

from django.db import migrations, models
import video_chat.models


class Migration(migrations.Migration):

    dependencies = [
        ('video_chat', '0007_alter_profile_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_avatar',
            field=models.ImageField(default='default_profile_avatar.jpg', upload_to=video_chat.models.avatar_upload_path),
        ),
    ]
