# Generated by Django 4.2.7 on 2023-11-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_chat', '0012_notification_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channeltype',
            name='type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='friendrequesttype',
            name='type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notificationstatus',
            name='status',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notificationtype',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
